name: Build debug APK

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!11-dev-localization'
      - '!11-alpha'

jobs:
  build-debug-apk:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Check out repository
        uses: actions/checkout@v2.3.4
        with:
          submodules: true
      - name: Restore Gradle cache
        uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Set up Java 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      - name: Grant execution permission to Gradle Wrapper
        run: chmod +x gradlew
      - name: Build debug APK
        run: ./gradlew assembleLawnWithQuickstepDebug
      - name: Sign debug APK
        uses: r0adkll/sign-android-release@v1
        id: sign-debug-apk
        with:
          releaseDirectory: build/outputs/apk/lawnWithQuickstep/debug
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Debug APK
          path: ${{ steps.sign-debug-apk.outputs.signedReleaseFile }}
